# Generated by Django 4.2.2 on 2023-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginre', '0002_remove_userprofile_avatar_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='+7', max_length=20),
        ),
    ]
