# Generated by Django 4.2.2 on 2023-06-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginre', '0003_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
