# Generated by Django 4.2.2 on 2023-06-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginre', '0004_remove_userprofile_bio_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
