# Generated by Django 4.2.2 on 2023-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginre', '0005_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
    ]
